### ISSUE TITLE
Different mods installed between server and client when running through docker

### ISSUE THREAD

**Issue by XanderRiga** [adam9899/MC-Eternal-2#16]
This is my docker compose:
```yml
services:
  mc_eternal:
    container_name: mc_eternal
    image: itzg/minecraft-server:java17
    mem_limit: 16384m
    environment:
      VERSION: 1.20.1
      MEMORY: 16G
      TYPE: FORGE
      ENABLE_ROLLING_LOGS: "true"
      EULA: "true"
      MODPACK: "https://github.com/adam9899/MC-Eternal-2/releases/download/v1.0/MCE2-Server-Files-1.0.zip"
    ports:
      - "25585:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
```

There are no errors in the logs and the server appears to be stable, but when someone tries to join, they see this:

![Image](https://github.com/user-attachments/assets/ec556b05-9b4a-4b26-b937-8b9339a5910a)
![Image](https://github.com/user-attachments/assets/7ca39f9c-d7bd-495f-9aa5-c1ddba7a9db9)

**Comment by XanderRiga** [comment]
I resolved this problem by using `TYPE: CUSTOM` and setting the `CUSTOM_SERVER` to a jar that I downloaded [here](https://www.curseforge.com/minecraft/mc-mods/forge-server-starter)

```
services:
  mc_eternal:
    container_name: mc_eternal
    image: itzg/minecraft-server:java17
    environment:
      VERSION: 1.20.1
      MEMORY: 16G
      TZ: UTC
      EULA: "true"
      TYPE: CUSTOM
      CUSTOM_SERVER: /data/minecraft_server_v3.5.7.jar
    ports:
      - "25585:25565"
    volumes:
      - ./data/MCE2-Server-Files-1.0:/data
    restart: unless-stopped
```
